############################
# Site basics
############################
baseURL = "https://frostfir.com/"
languageCode = "en-us"
title = "Frostfir"
theme = "WonderMod"
enableRobotsTXT = true

############################
# Pagination
############################
[pagination]
  pagerSize = 10

############################
# Taxonomies (for #tags)
############################
[taxonomies]
  tag = "tags"

############################
# Outputs (required for search)
############################
[outputs]
  home = ["HTML", "RSS", "JSON"]

############################
# Main site parameters
############################
[params]
  description = "Experiments, documentation, and privacy-conscious publishing."
  mainSections = ["posts"]
  enableSearch = true

############################
# Header label / logo
############################
[params.label]
  text = "Frostfir"
  icon = "/images/frostfir-logo.png"
  iconHeight = 24

############################
# Home page intro block
############################
[params.homeInfoParams]
Title = "Frostfir"
Content = """
An experimental site for testing ideas, documenting setups,
and exploring simple, privacy-conscious publishing.
"""

############################
# Social metadata (used for cards, not icons)
############################
[params.social]
  twitter = ""
  facebook_admin = ""

############################
# Social icons (homepage)
############################
[[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/aqibu"

[[params.socialIcons]]
  name = "mastodon"
  url = "https://YOUR_INSTANCE/@YOUR_USERNAME"

[[params.socialIcons]]
  name = "bluesky"
  url = "https://bsky.app/profile/YOUR_HANDLE"

############################
# Main menu
############################
[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Privacy"
  url = "/privacy/"
  weight = 3

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 4
