baseURL = "https://frostfir.com/"
languageCode = "en-us"
title = "Frostfir"
theme = "WonderMod"

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  description = "Experiments and things I'm trying."

[params.social]
  twitter = ""          # optional, without @ (e.g. "aqibu")
  facebook_admin = ""   # optional

[params.homeInfoParams]
Title = "Frostfir"
Content = """
A small experimental site for testing ideas, documenting setups,
and exploring simple, privacy-conscious publishing on the web.
"""

mainSections = ["posts"]

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/aqibu"

[[params.socialIcons]]
name = "mastodon"
url = "https://YOUR_INSTANCE/@YOUR_USERNAME"

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/YOUR_HANDLE"

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Privacy"
url = "/privacy/"
weight = 3
