baseURL = "https://frostfir.com/"
languageCode = "en-us"
title = "Frostfir"
theme = "WonderMod"

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  description = "Experiments and things I'm trying."

[params.social]
  twitter = ""          # optional, without @ (e.g. "aqibu")
  facebook_admin = ""   # optional
